/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BancoRouteImport } from './routes/banco'
import { Route as DesempenhoRouteImport } from './routes/desempenho'
import { Route as ProvaRouteImport } from './routes/prova'
import { Route as ResultadoRouteImport } from './routes/resultado'
import { Route as TreinoRouteImport } from './routes/treino'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BancoRoute = BancoRouteImport.update({
  id: '/banco',
  path: '/banco',
  getParentRoute: () => rootRouteImport,
} as any)
const DesempenhoRoute = DesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvaRoute = ProvaRouteImport.update({
  id: '/prova',
  path: '/prova',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadoRoute = ResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoRoute = TreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banco': typeof BancoRoute
  '/desempenho': typeof DesempenhoRoute
  '/prova': typeof ProvaRoute
  '/resultado': typeof ResultadoRoute
  '/treino': typeof TreinoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banco': typeof BancoRoute
  '/desempenho': typeof DesempenhoRoute
  '/prova': typeof ProvaRoute
  '/resultado': typeof ResultadoRoute
  '/treino': typeof TreinoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banco': typeof BancoRoute
  '/desempenho': typeof DesempenhoRoute
  '/prova': typeof ProvaRoute
  '/resultado': typeof ResultadoRoute
  '/treino': typeof TreinoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/banco' | '/desempenho' | '/prova' | '/resultado' | '/treino'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/banco' | '/desempenho' | '/prova' | '/resultado' | '/treino'
  id:
    | '__root__'
    | '/'
    | '/banco'
    | '/desempenho'
    | '/prova'
    | '/resultado'
    | '/treino'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BancoRoute: typeof BancoRoute
  DesempenhoRoute: typeof DesempenhoRoute
  ProvaRoute: typeof ProvaRoute
  ResultadoRoute: typeof ResultadoRoute
  TreinoRoute: typeof TreinoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banco': {
      id: '/banco'
      path: '/banco'
      fullPath: '/banco'
      preLoaderRoute: typeof BancoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desempenho': {
      id: '/desempenho'
      path: '/desempenho'
      fullPath: '/desempenho'
      preLoaderRoute: typeof DesempenhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prova': {
      id: '/prova'
      path: '/prova'
      fullPath: '/prova'
      preLoaderRoute: typeof ProvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultado': {
      id: '/resultado'
      path: '/resultado'
      fullPath: '/resultado'
      preLoaderRoute: typeof ResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino': {
      id: '/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof TreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BancoRoute: BancoRoute,
  DesempenhoRoute: DesempenhoRoute,
  ProvaRoute: ProvaRoute,
  ResultadoRoute: ResultadoRoute,
  TreinoRoute: TreinoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
